LIBDRM_SGPU_FILES := \
	amdgpu_asic_id.c \
	amdgpu_bo.c \
	amdgpu_cs.c \
	amdgpu_device.c \
	amdgpu_gpu_info.c \
	amdgpu_internal.h \
	amdgpu_vamgr.c \
	amdgpu_vm.c \
	handle_table.c \
	handle_table.h \
	sgpu_trace.c \
	sgpu_sysfs.c

LIBDRM_SGPU_H_FILES := \
	amdgpu.h
